#!/bin/bash

set -e

if [ "$EUID" -ne 0 ]; then
    echo "This script uses functionality which requires root privileges"
    exit 1
fi

BINARYDIR=${BINARYDIR:-bin}
BUILDDIR=${BUILDDIR:-bin}

VERSION=$1

if ! command -v $ACBUILD >/dev/null; then
    echo "acbuild ($ACBUILD) is not executable"
    exit 1
fi

if [ ! -x $BINARYDIR/errand-boy ] ; then
    echo "$BINARYDIR/errand-boy not found. Is it compiled?"
    exit 1
fi

if [ -z "$VERSION" ] ; then
    echo "Usage: scripts/build-aci VERSION"
    exit 1
fi

acbuild --debug begin

TMPHOSTS="$(mktemp)"

trap "{ export EXT=$?; rm "$TMPHOSTS" && acbuild --debug end && exit $EXT; }" EXIT

cat <<DF > $TMPHOSTS
208.85.149.36 www.pivotaltracker.com
DF

acbuild --debug set-name barista-v.com/errand-boy
acbuild --debug dep add quay.io/sameersbn/ubuntu
acbuild --debug copy "$TMPHOSTS" /etc/hosts
acbuild --debug copy errand-boy /bin/errand-boy
acbuild --debug copy eb.conf.json /bin/eb.conf.json
acbuild --debug set-exec -- /bin/errand-boy -p 8080 -c /bin/eb.conf.json
acbuild --debug port add www tcp 8080
acbuild --debug label add version "$VERSION"
acbuild --debug label add arch amd64
acbuild --debug label add os linux
acbuild --debug write --overwrite $BUILDDIR/errand-boy-${1}-linux-amd64.aci
